#serenity.project.name=SerenityBDD
#serenity.test.root=com.devsu
#
#webdriver.driver=chrome
#webdriver.autodownload=true
#serenity.browser.maximazed=true
#
#serenity.use.unique.browser=false
#serenity.restart.browser.each.scenario=true
#
#serenity.maintain.session=true
#
#serenity.outputDirectory=target/site/serenity
#serenity.reports=single-page-html
